name: pull-request-tests
on:
  pull_request:
    branches:
      - main
jobs:
  pr-run-storybook-tests:
    timeout-minutes: 5 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'
          always-auth: true
      - run: echo "Running npm CI command"
      - run: echo "Running npx playwright install-deps webkit command" 
      - name: Test Storybook 
        run: echo "Running npm run test:storybook"
        env:
          CI: true